# Generated by Django 3.2.9 on 2022-07-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolloutapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
