# Generated by Django 3.2.9 on 2022-07-20 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rolloutapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('picture', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('experience', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=10)),
                ('dexterity', models.IntegerField(default=10)),
                ('constitution', models.IntegerField(default=10)),
                ('intelligence', models.IntegerField(default=10)),
                ('wisdom', models.IntegerField(default=10)),
                ('charisma', models.IntegerField(default=10)),
                ('proficiency_bonus', models.IntegerField(default=2)),
                ('hit_points', models.IntegerField(default=8)),
                ('temp_hit_points', models.IntegerField(default=0)),
                ('armor_class', models.IntegerField(default=10)),
                ('alignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_characters', to='rolloutapi.alignment')),
                ('character_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_characters', to='rolloutapi.characterclass')),
                ('languages', models.ManyToManyField(related_name='default_characters', to='rolloutapi.Language')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_characters', to='rolloutapi.subrace')),
                ('skills', models.ManyToManyField(related_name='default_characters', to='rolloutapi.Skill')),
            ],
        ),
    ]
