# Generated by Django 3.2.9 on 2022-07-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolloutapi', '0002_remove_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='classes',
            field=models.ManyToManyField(related_name='spells', to='rolloutapi.CharacterClass'),
        ),
    ]
