# Generated by Django 3.2.9 on 2022-07-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolloutapi', '0002_defaultcharacter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterclass',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
