# Generated by Django 3.2.9 on 2022-07-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolloutapi', '0003_alter_characterclass_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterclass',
            old_name='hitdice',
            new_name='hit_dice',
        ),
    ]
