# Generated by Django 3.2.9 on 2022-07-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolloutapi', '0003_spell_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
