# Generated by Django 3.2.9 on 2022-07-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolloutapi', '0004_spell_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('level', models.IntegerField(default=1)),
                ('custom', models.BooleanField(default=False)),
                ('classes', models.ManyToManyField(related_name='feats', to='rolloutapi.CharacterClass')),
            ],
        ),
    ]
