# Generated by Django 3.2.9 on 2022-07-20 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolloutapi', '0004_rename_hitdice_characterclass_hit_dice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='picture',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='defaultcharacter',
            old_name='picture',
            new_name='image',
        ),
    ]
