# Generated by Django 3.2.9 on 2022-07-26 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rolloutapi', '0005_feat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subrace',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_races', to='rolloutapi.size'),
        ),
    ]
