# Generated by Django 3.2.9 on 2022-07-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rolloutapi', '0006_auto_20220720_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultcharacter',
            name='temp_hit_points',
        ),
    ]
