# Generated by Django 3.2.9 on 2022-07-26 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolloutapi', '0006_alter_subrace_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='characters',
            field=models.ManyToManyField(related_name='spells', to='rolloutapi.Character'),
        ),
    ]
