# Generated by Django 3.2.9 on 2022-07-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolloutapi', '0007_remove_defaultcharacter_temp_hit_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='ranged',
            field=models.BooleanField(default=False),
        ),
    ]
