# Generated by Django 3.2.9 on 2022-07-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolloutapi', '0008_weapon_ranged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='damage',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='two_handed_damage',
            field=models.CharField(max_length=5),
        ),
    ]
