# Generated by Django 3.2.9 on 2022-08-19 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rolloutapi', '0009_characteritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteritem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='characterItems', to='rolloutapi.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='characteritem',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characterItems', to='rolloutapi.character'),
        ),
    ]
