# Generated by Django 3.2.9 on 2022-08-21 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rolloutapi', '0010_auto_20220819_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='characters',
            field=models.ManyToManyField(related_name='weapons', to='rolloutapi.Character'),
        ),
        migrations.AlterField(
            model_name='characteritem',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_items', to='rolloutapi.character'),
        ),
        migrations.AlterField(
            model_name='characteritem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_items', to='rolloutapi.item'),
        ),
    ]
