# Generated by Django 3.2.9 on 2022-08-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolloutapi', '0011_auto_20220821_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='characters',
            field=models.ManyToManyField(related_name='armor', to='rolloutapi.Character'),
        ),
    ]
