# Generated by Django 3.2.9 on 2022-08-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rolloutapi', '0012_armor_characters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='cp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='money',
            name='gp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='money',
            name='sp',
            field=models.IntegerField(default=0),
        ),
    ]
